#服务端口
server:
  port: 8082

#服务注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

#spring设置
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaochenpeng/springCloud.git
          username: "243150929@qq.com"
          password: "lcp243150929"
          skip-ssl-validation: true
          default-label: main
          searchPaths: config-rep